# Cleanup of an exported engine graph (SPARQL 1.1 Update), applied before the lifted triples are
# added. It removes the statements that the lift rules replace, the predicates no vocabulary
# declares, and the types that RDFS entailment derives from the engine's domain and range
# conflicts (for example a data split activity typed aidoc:Dataset because of aidoc:dataScope).
# A live SPARQL endpoint of the engine is read-only; there the lifted graph is used next to the
# unchanged engine graph and these statements remain.

PREFIX aidoc: <https://w3id.org/aidoc-ap#>
PREFIX airo: <https://w3id.org/airo#>
PREFIX dcat: <https://www.w3.org/ns/dcat#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dqv: <http://www.w3.org/ns/dqv#>
PREFIX mls: <http://www.w3.org/ns/mls#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# Activities are not entities (PROV): remove entity types inferred from domain conflicts.
DELETE { ?x a ?t }
WHERE {
  ?x a prov:Activity .
  ?x a ?t .
  VALUES ?t { prov:Entity aidoc:AIArtifact aidoc:Dataset mls:Dataset dcat:Dataset aidoc:AISystem aidoc:DataSheet }
} ;

# Measurement rows are not metrics or datasets.
DELETE { ?x a ?t }
WHERE {
  ?x dqv:computedOn ?target .
  ?x a ?t .
  VALUES ?t { aidoc:PerformanceMetric dqv:Metric aidoc:AIArtifact aidoc:Dataset mls:Dataset dcat:Dataset }
} ;

# aidoc:dataScope (domain aidoc:Dataset) on activities, measurements and prediction examples.
DELETE { ?x aidoc:dataScope ?v }
WHERE {
  ?x aidoc:dataScope ?v .
  { ?x a prov:Activity } UNION { ?x a aidoc:AIActivity } UNION { ?x dqv:computedOn ?t }
  UNION { FILTER (CONTAINS(STR(?x), "/example/")) }
} ;

# aidoc:dataCollectionMethod (domain aidoc:Dataset) on activities: moved to the dataset by rule 17,
# turned into processingTechnique by rule 18. On datasets it was written by the engine's
# DataTechniquesTriplesMap from technique names, so it is removed there as well and only the
# value moved from the acquisition activity (rule 17) remains.
DELETE { ?x aidoc:dataCollectionMethod ?v } WHERE { ?x aidoc:dataCollectionMethod ?v } ;

# aidoc:version (domain prov:Entity) on activities: moved to the model or code by rules 7, 8, 15.
DELETE { ?x aidoc:version ?v }
WHERE {
  ?x aidoc:version ?v ; a ?t .
  VALUES ?t { prov:Activity aidoc:AIActivity aidoc:ModelVersioning aidoc:SoftwareVersioning aidoc:Deployment }
} ;

# aidoc:hasLifecycleStage (domain aidoc:AISystem) on experiments and deployments: rules 8 and 19.
DELETE { ?x aidoc:hasLifecycleStage ?v }
WHERE { ?x aidoc:hasLifecycleStage ?v . { ?x a aidoc:ModelEngineering } UNION { ?x a aidoc:Deployment } } ;

# Activity predicates on non-activities: lifecycle phases and change records.
DELETE { ?x ?p ?v }
WHERE {
  ?x ?p ?v .
  { ?x a airo:AILifecyclePhase . VALUES ?p { prov:startedAtTime prov:endedAtTime } }
  UNION
  { ?x a aidoc:ChangeRecord . VALUES ?p { prov:endedAtTime prov:wasAssociatedWith } }
} ;
DELETE { ?x a prov:Activity } WHERE { ?x a prov:Activity . { ?x a aidoc:ChangeLog } UNION { ?x a airo:AILifecyclePhase } } ;

# Predicates declared nowhere, after rules 3 and 13 have lifted their content.
DELETE { ?x ?p ?v }
WHERE { ?x ?p ?v . VALUES ?p { mls:hasObjective mls:hasOptimizer mls:hasModelParameter prov:wasUsedBy } } ;

# Hyperparameter rows point with mls:specifiedBy to the model instead of the hyperparameter (rule 2).
DELETE { ?s mls:specifiedBy ?m } WHERE { ?s mls:specifiedBy ?m . ?m a aidoc:AIModel } ;

# Resources "require" hardware (domain aidoc:AISystem or aidoc:AIArtifact): rule 13 states the
# core relation in its declared direction.
DELETE { ?r aidoc:requiresHardware ?h } WHERE { ?r aidoc:requiresHardware ?h . ?r a aidoc:ComputationalResource } ;

# Drift rows computed on the deployment activity: rule 11 states them on the model.
DELETE { ?x dqv:computedOn ?dep } WHERE { ?x dqv:computedOn ?dep . ?dep a aidoc:Deployment } ;

# A run "generated" a deployment (an activity) through id_mapping.
DELETE { ?run prov:generated ?dep }
WHERE { ?run prov:generated ?dep . FILTER (REGEX(STR(?dep), "^https://w3id.org/aidoc-ap/deployments/[^/]+/[^/]+/[^/]+$")) } ;

# Prediction examples "generated" by a model (rule 19 states run and model).
DELETE { ?ex prov:wasGeneratedBy ?m } WHERE { ?ex prov:wasGeneratedBy ?m . ?m a aidoc:AIModel } ;

# The software implementation is executed by the run, not generated by it (rule 14).
DELETE { ?c prov:wasGeneratedBy ?run } WHERE { ?c a aidoc:SoftwareImplementation ; prov:wasGeneratedBy ?run } ;

# aidoc:hasAIActivity (domain airo:AILifecyclePhase) on the AI system (rule 19).
DELETE { ?s aidoc:hasAIActivity ?a } WHERE { ?s aidoc:hasAIActivity ?a . ?s a aidoc:AISystem } ;

# Runtime environment rows typed as re-evaluation activities by the engine: no re-evaluation took place.
DELETE { ?x ?p ?o }
WHERE { ?x a aidoc:PostMarketPerformanceEvaluationActivity ; ?p ?o .
        FILTER (STRSTARTS(STR(?x), "https://w3id.org/aidoc-ap/post-market-performance/")) } ;

# aidoc:VisualDocumentation was renamed in core v1.2 (rule 19 adds aidoc:TechnicalDocumentation).
DELETE { ?x a aidoc:VisualDocumentation } WHERE { ?x a aidoc:VisualDocumentation }
