#!/usr/bin/env python3
"""Check the alignment proposals and write them in the record format of the core alignments.

Input: alignments/proposed.ttl, one SKOS mapping per line followed by "# rationale".
Checks (exit code 1 on failure):
  - the file parses and every mapping line is a triple in the parsed graph
  - the subject is a term of the module, the relation a SKOS mapping property
  - the target is declared in the AIDOC-AP core or in the vendored reference ontologies
  - every mapping has a rationale
Output: alignments/proposed-reified.ttl with one align:Mapping record per mapping, as in the
core's docs/resources/*-alignments.ttl, generated by a proposal activity and without a
curation outcome (curation is pending).

  python3 scripts/alignments.py
"""
from __future__ import annotations

import argparse
import re
import sys
import uuid

from rdflib import Graph, Literal, Namespace, URIRef
from rdflib.namespace import PROV, RDF, RDFS, SKOS, XSD

from common import CORE_TTL, LC_NS, MODULE_TTL, ROOT, load_graph, reference_graph

ALIGN = Namespace("https://w3id.org/aidoc-ap/alignment#")
REC = Namespace("https://w3id.org/aidoc-ap/lifecycle/alignment/")
RELATIONS = {SKOS.exactMatch, SKOS.closeMatch, SKOS.broadMatch, SKOS.narrowMatch, SKOS.relatedMatch}
LINE = re.compile(r"^(\S+)\s+(\S+)\s+(\S+)\s*\.\s*#\s*(.+)$")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--src", default=str(ROOT / "alignments" / "proposed.ttl"))
    ap.add_argument("--out", default=str(ROOT / "alignments" / "proposed-reified.ttl"))
    ap.add_argument("--date", default="2026-10-05", help="date of the proposal activity")
    args = ap.parse_args()

    g = Graph()
    g.parse(args.src)
    module = load_graph([MODULE_TTL])
    known = load_graph([CORE_TTL]) + reference_graph()
    nm = g.namespace_manager

    def expand(token: str) -> URIRef:
        if token.startswith("<"):
            return URIRef(token[1:-1])
        prefix, local = token.split(":", 1)
        ns = dict(nm.namespaces()).get(prefix)
        if ns is None:
            raise ValueError(f"unknown prefix in '{token}'")
        return URIRef(str(ns) + local)

    errors, mappings = [], []
    for n, line in enumerate(open(args.src, encoding="utf-8"), 1):
        if not line.strip() or line.lstrip().startswith(("#", "@prefix")):
            continue
        m = LINE.match(line.strip())
        if not m:
            errors.append(f"line {n}: expected 'subject relation target .  # rationale'")
            continue
        s, p, o = (expand(t) for t in m.group(1, 2, 3))
        rationale = m.group(4).strip()
        if (s, p, o) not in g:
            errors.append(f"line {n}: triple not in parsed graph")
        if not str(s).startswith(LC_NS) or (s, None, None) not in module:
            errors.append(f"line {n}: subject {s} is not a module term")
        if p not in RELATIONS:
            errors.append(f"line {n}: {p} is not a SKOS mapping property")
        if (o, None, None) not in known:
            errors.append(f"line {n}: target {o} is not declared in the core or the reference ontologies")
        mappings.append((s, p, o, rationale))

    parsed = {(s, p, o) for s, p, o in g if p in RELATIONS}
    if parsed != {(s, p, o) for s, p, o, _ in mappings}:
        errors.append("the parsed graph holds mappings that are not on a line of their own")

    for e in errors:
        print("ERROR:", e)
    if errors:
        return 1

    out = Graph()
    for prefix, ns in [("align", ALIGN), ("rec", REC), ("prov", PROV), ("skos", SKOS), ("rdfs", RDFS),
                       ("xsd", XSD), ("aidoc-lc", Namespace(LC_NS))]:
        out.bind(prefix, ns)
    for prefix, ns in nm.namespaces():
        if prefix not in ("", "rdf", "rdfs", "xsd", "xml", "owl"):
            out.bind(prefix, ns)
    agent = REC["LifecycleExtensionMaintainers"]
    out.add((agent, RDF.type, PROV.Agent))
    out.add((agent, RDFS.label, Literal("AIDOC-AP Lifecycle Extension maintainers")))
    activity = REC["proposal-" + args.date]
    out.add((activity, RDF.type, PROV.Activity))
    out.add((activity, RDFS.label, Literal("Proposal of alignments for the AIDOC-AP Lifecycle Extension, awaiting expert curation")))
    out.add((activity, PROV.startedAtTime, Literal(args.date, datatype=XSD.date)))
    out.add((activity, PROV.wasAssociatedWith, agent))
    for s, p, o, rationale in mappings:
        rec = REC[str(uuid.uuid5(uuid.NAMESPACE_URL, f"{s} {p} {o}"))]
        out.add((rec, RDF.type, PROV.Entity))
        out.add((rec, RDF.type, ALIGN.Mapping))
        out.add((rec, ALIGN.source, s))
        out.add((rec, ALIGN.relation, p))
        out.add((rec, ALIGN.target, o))
        out.add((rec, RDFS.comment, Literal(rationale, lang="en")))
        out.add((rec, PROV.wasGeneratedBy, activity))
        out.add((rec, PROV.wasAttributedTo, agent))
    header = ("# Generated by scripts/alignments.py from alignments/proposed.ttl. Do not edit by hand.\n"
              "# Record format of the AIDOC-AP core alignments; align:curationOutcome is added by the curation.\n")
    open(args.out, "w", encoding="utf-8").write(header + out.serialize(format="turtle"))
    print(f"{len(mappings)} mapping(s) checked; written to {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
